name: IP Check Action

on:
  workflow_dispatch:

jobs:
  check_ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.IP_Check_PAT }}  # Use the GITHUB_TOKEN to get push access.

      - name: Install Cloudflare WARP
        run: |
          wget -O wgcf https://github.com/ViRb3/wgcf/releases/download/v2.2.18/wgcf_2.2.18_linux_amd64
          chmod +x wgcf
          sudo mv wgcf /usr/local/bin/wgcf
          wgcf register --accept-tos
          wgcf generate
          sudo apt install wireguard resolvconf
          sudo cp wgcf-profile.conf /etc/wireguard/wgcf.conf
          sudo wg-quick up wgcf

      - name: Check GitHub Action IPv6 Support
        run: |
          if ping6 -c 1 2001:4860:4860::8888; then
            echo "GitHub Action environment supports IPv6."
          else
            echo "GitHub Action environment does not support IPv6."
            exit 1
          fi

      - name: Convert IPv6s and Check availability
        run: |
          curl -s https://raw.githubusercontent.com/XIU2/CloudflareSpeedTest/master/ipv6.txt -o ipv6.txt
          python3 ./ipv6_check_script.py
      
      - name: Convert IPv4s and Check availability
        run: |
          curl -s https://raw.githubusercontent.com/XIU2/CloudflareSpeedTest/master/ip.txt -o ip.txt
          python3 ./ipv4_check_script.py
      
      # 下面的步骤用于提交和推送 reachable_ips.txt 和 bind_config.txt 文件的更新到仓库
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add whole_ips.txt reachable_ips.txt simple_reachable_ips.txt bind_config.txt ipv6_whole_ips.txt ipv6_reachable_ips.txt ipv6_simple_reachable_ips.txt ipv6_bind_config.txt
          git commit -m "Update whole_ips.txt reachable_ips.txt simple_reachable_ips.txt bind_config.txt"
          git push
      
      - name: Upload Result
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: |
            whole_ips.txt
            reachable_ips.txt
            simple_reachable_ips.txt
            bind_config.txt
            ipv6_whole_ips.txt
            ipv6_reachable_ips.txt
            ipv6_simple_reachable_ips.txt
            ipv6_bind_config.txt
