name: IP Check Action

on:
  workflow_dispatch:  # 这允许手动触发GitHub Action

jobs:
  check_ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Convert IPs and Check availability
        run: |
          curl -s https://raw.githubusercontent.com/XIU2/CloudflareSpeedTest/master/ip.txt -o ip.txt
          python3 ./ip_check_script.py
      
      - name: Upload Result
        uses: actions/upload-artifact@v3
        with:
          name: reachable-ips
          path: reachable_ips.txt
