name: IP Check Action

on:
  push:
    branches:
      - main

jobs:
  check_ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install tcping
        run: |
          sudo apt-get update
          sudo apt-get install -y tcptraceroute
          echo 'tcping() { /usr/sbin/tcptraceroute -f 255 -m 255 -q 1 "$@"; }' | sudo tee -a /etc/bash.bashrc
          source /etc/bash.bashrc
      
      - name: Convert IPs and Check availability
        run: |
          curl -s https://raw.githubusercontent.com/XIU2/CloudflareSpeedTest/master/ip.txt -o ip.txt
          python3 ./ip_check_script.py
